import {createRequire} from 'node:module';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
import {openDatabase} from '../server/local-db.js';
import worker from '../server/worker.js';
const require=createRequire(import.meta.url);
const {chromium}=require('/Users/kenniethallen/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=resolve(import.meta.dirname,'..'),out=resolve(root,'qa');mkdirSync(out,{recursive:true});
const DB=openDatabase(':memory:');DB.raw.exec(readFileSync(resolve(root,'db/001_poll.sql'),'utf8'));
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'};
const env={DB,POLL_ENABLED:'true',PREVIEW_MODE:'true',POLL_SECRET:'offline-test-secret-thirty-two-characters',ASSETS:{async fetch(req){let path=new URL(req.url).pathname;if(path==='/')path='/index.html';try{return new Response(readFileSync(resolve(root,'dist','.'+path)),{headers:{'Content-Type':mime[extname(path)]||'application/octet-stream'}});}catch{return new Response('Not found',{status:404});}}}};
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
await context.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(tool){window.registeredTools[tool.name]=tool;}}});});
let forceFailure=false;
await context.route('**/*',async route=>{const r=route.request();if(!r.url().startsWith('https://mighty.test/'))return route.abort();if(forceFailure&&r.url().endsWith('/api/poll'))return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Test interruption; please retry.'})});const req=new Request(r.url(),{method:r.method(),headers:r.headers(),...(['GET','HEAD'].includes(r.method())?{}:{body:r.postDataBuffer()})});const response=await worker.fetch(req,env);await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('https://mighty.test/');await page.getByText('Local review mode.',{exact:false}).waitFor();await page.evaluate(async()=>{for(const img of document.images)img.loading='eager';await Promise.all([...document.images].map(img=>img.decode()));});
for(const [width,height] of [[1440,1000],[768,1024],[390,844],[320,740]]){await page.setViewportSize({width,height});await page.screenshot({path:resolve(out,`page-${width}.png`),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`No overflow at ${width}`);}
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Next question'}).click();await page.getByRole('alert').filter({hasText:'Please choose an answer.'}).waitFor();
await page.getByLabel('Shop / barn',{exact:true}).check();await page.getByRole('button',{name:'Next question'}).click();
await page.getByLabel('Work vehicle',{exact:true}).check();await page.getByRole('button',{name:'Next question'}).click();
await page.getByLabel('Bleeding / cuts',{exact:true}).check();await page.getByRole('button',{name:'Next question'}).click();
await page.getByLabel('Portability',{exact:true}).check();await page.getByLabel('Accessibility',{exact:true}).check();await page.getByRole('button',{name:'Next question'}).click();
await page.getByLabel('Depends on where / how I could store it',{exact:true}).check();await page.getByRole('button',{name:'Next question'}).click();
await page.getByLabel('Your feedback (optional)').fill('Offline UI test only.');await page.getByRole('button',{name:'Continue',exact:false}).click();
forceFailure=true;await page.getByRole('button',{name:'Submit my response'}).click();await page.getByRole('alert').filter({hasText:'Test interruption'}).waitFor();assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM responses').get().n,0);
forceFailure=false;await page.getByRole('button',{name:'Try submitting again'}).click();await page.getByRole('heading',{name:'Thank you for sharing your experience.'}).waitFor();
await page.getByRole('button',{name:'See aggregate results'}).click();await page.getByText('1 local test response.',{exact:false}).waitFor();await page.screenshot({path:resolve(out,'results-mobile.png'),fullPage:true});
await page.reload();await page.getByRole('heading',{name:'A response is already recorded for this browser.'}).waitFor();
const toolResult=await page.evaluate(async()=>{const tool=window.registeredTools.start_farm_readiness_poll;const result=await tool.execute({});let rejected=false;try{await tool.execute({unexpected:true});}catch{rejected=true;}return {name:tool.name,result,rejected};});assert.equal(toolResult.rejected,true);assert.equal(toolResult.result.submitted,true);
await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'200% text no overflow');await page.screenshot({path:resolve(out,'text-200-mobile.png'),fullPage:true});
assert.deepEqual(errors,[]);writeFileSync(resolve(out,'report.json'),JSON.stringify({viewports:[1440,768,390,320],form:'validation, anonymous submission, retry, duplicate and aggregate results passed',webMCP:'registration and valid/invalid calls passed with test shim; native support not available',consoleErrors:errors},null,2));
await browser.close();DB.close();console.log('Offline browser QA passed; no HTTP listener started. Screenshots in site/qa.');
